name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  id-token: write # for attestations
  contents: write # for update release assets
  attestations: write # for attestations

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "dist/**/tfustomize*"
          subject-name: "tk3fftk/tfustomize"
