name: Go Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Install dependencies
        run: go get .
      - name: Unit Test
        run: go test -v ./...
      - name: Build
        run: go build
      - name: goreleaser snapshot
        run: |
          go install github.com/goreleaser/goreleaser@latest
          goreleaser release --snapshot --clean
